SELECT * FROM Paciente

BEGIN TRAN
	UPDATE Paciente SET telefono = 444 WHERE idPaciente=8
IF @@ROWCOUNT = 1 --INDICA CUANTOS REGISTROS FUERON MODIFICADOS EN LA INSTRUCCION ANTERIOR. 
	COMMIT TRAN
ELSE
	ROLLBACK TRAN


BEGIN TRAN
	UPDATE Paciente SET telefono = 444 WHERE apellido = 'Perez'
IF @@ROWCOUNT = 1 --INDICA CUANTOS REGISTROS FUERON MODIFICADOS EN LA INSTRUCCION ANTERIOR. 
	COMMIT TRAN
ELSE
	ROLLBACK TRAN
