SELECT * FROM Turno

INSERT INTO Turno VALUES (GETDATE(),1,'')

BEGIN TRAN
	DELETE FROM Turno WHERE estado=1
IF @@ROWCOUNT = 1
	COMMIT TRAN
ELSE
	ROLLBACK TRAN

INSERT INTO Turno VALUES (GETDATE(),1,'')